language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
services:
  - memcached
install:
  - composer self-update
  - composer install
before_script:
  - tests/bin/memcached.sh
script:
  - chmod -R 777 tests/logs
  - phpunit
after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/coveralls -v; fi
