sudo: false
language: php
php:
  - 5.5
  - 5.6
  - hhvm
services:
  - memcached
before_script:
  - composer self-update
  - composer install --prefer-source
  - chmod -R 755 tests/bin/memcached.sh
  - tests/bin/memcached.sh
script:
  - chmod -R 777 tests/logs
  - phpunit
after_script:
  - php vendor/bin/coveralls -v
