sudo: false
language: php
php:
  - 7.0
  - 7.1
services:
  - redis-server
  - memcached
before_script:
  - composer self-update
  - composer install --prefer-source
  - chmod -R 755 tests/bin/memcached.sh
  - tests/bin/memcached.sh
script:
  - chmod -R 777 tests/build
  - ./vendor/bin/phpunit --coverage-clover tests/build/clover.xml
  - chmod 777 tests/build/clover.xml
after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php vendor/bin/coveralls -v; fi
